/* =========================================================
   SINGLE SOURCE OF TRUTH — Riley McClain's experience
   ---------------------------------------------------------
   Add or edit a role here and BOTH the Experience page and
   the Home page stats update automatically.

   Each entry:
     title    — job title
     company  — organization
     location — city / remote
     start    — "YYYY-MM" (used for sorting)
     end      — "YYYY-MM" or "Present"
     date     — human-readable range shown on the card
     type     — "work" or "internship" (for counts/labels)
     bullets  — array of accomplishment strings
   Keep the list in reverse-chronological order (newest first).
   ========================================================= */
window.EXPERIENCES = [
  {
    title: "Developer I",
    company: "Compassion International",
    location: "Colorado Springs",
    start: "2025-08",
    end: "Present",
    date: "Aug 2025 – Present",
    type: "work",
    bullets: [
      "Finished a Knowledge Library in Salesforce Experience built on a highly engaging UI.",
      "Worked with a team of 5 other developers maintaining and updating Salesforce.",
      "Operated in a SAFe agile framework — DSUs, demos, retros, and PI planning.",
      "Engaged clients regularly to understand and build the product they wanted, collaborating with UX for the best user experience.",
      "Built custom Lightning Web Components that integrate with each other and with out-of-the-box Salesforce Experience.",
      "Used AWS EventBridge to connect external APIs that update and create Salesforce data.",
      "Fixed bugs and resolved end-user tickets within a week of submission.",
    ],
  },
  {
    title: "Software Developer (Part-time)",
    company: "ST&G",
    location: "Brea, Remote",
    start: "2025-03",
    end: "Present",
    date: "Mar 2025 – Present",
    type: "work",
    bullets: [
      "Developed a Google AppSheet allowing users to track and follow progress across different projects.",
      "Updated and maintained an e-commerce WordPress website.",
      "Created staging sites through SiteGround for updates.",
      "Worked with end-users to bring requests from ideation to production.",
      "Collaborated across departments to deliver a product that met each department's needs.",
    ],
  },
  {
    title: "Solutions Engineering Intern III",
    company: "Compassion International",
    location: "Colorado Springs",
    start: "2024-05",
    end: "Present",
    date: "May 2024 – Present",
    type: "internship",
    bullets: [
      "Developed, in a team of 2, a Salesforce Lightning Knowledge page so Compassion could learn and understand different processes across the organization.",
      "Learned how Compassion's programs work and interact with overseas churches.",
      "Compiled relevant information and organized it in a user-friendly manner.",
      "Chosen in an elite group of 9 to stay on for an extended time to finish my project.",
    ],
  },
  {
    title: "Office Administrator, COE CSDS",
    company: "California Baptist University",
    location: "Riverside, CA",
    start: "2023-11",
    end: "2024-12",
    date: "Nov 2023 – Dec 2024",
    type: "work",
    bullets: [
      "Coordinated and promoted student-focused events and departmental activities to boost engagement, community participation, and interdepartmental relationships.",
      "Supported faculty with end-of-semester processes, including departmental paperwork and faculty and semester feedback/outcome surveys.",
      "Helped renew ABET accreditation by organizing required documentation, gathering assessment data, and coordinating with faculty for timely, accurate submissions.",
    ],
  },
  {
    title: "Mobile App Development Tutor",
    company: "California Baptist University",
    location: "Riverside, CA",
    start: "2024-07",
    end: "2024-12",
    date: "Jul 2024 – Dec 2024",
    type: "work",
    bullets: [
      "Debugged students' code, explained mistakes, and helped find solutions.",
      "Encouraged and ideated with students on new app ideas.",
    ],
  },
  {
    title: "Solutions Engineering Intern II",
    company: "Compassion International",
    location: "Colorado Springs",
    start: "2024-05",
    end: "2024-08",
    date: "May 2024 – Aug 2024",
    type: "internship",
    bullets: [
      "Worked in a small team of 3 to add features and fix issues in a CRM.",
      "Communicated with clients to produce the best solution and product.",
      "Developed in Salesforce using Apex, SOQL, Custom Metadata Types, and Lightning Web Components.",
      "Quickly resolved bugs and pushed to end users within a week.",
    ],
  },
  {
    title: "Solutions Engineering Intern II",
    company: "Compassion International",
    location: "Remote",
    start: "2023-05",
    end: "2023-09",
    date: "May 2023 – Sep 2023",
    type: "internship",
    bullets: [
      "Mentored by six software developers on full-stack development, specifically front-end and component libraries.",
      "Engaged with UX experts to create a user-friendly mobile application.",
      "Designed prototypes in a group of three to refine a fast-iterating prototype process.",
      "Fixed UI bugs and pushed code to development on Beneficiary Photos.",
    ],
  },
  {
    title: "Information Technology Manager",
    company: "California Baptist University",
    location: "Riverside, CA",
    start: "2022-07",
    end: "2023-05",
    date: "Jul 2022 – May 2023",
    type: "work",
    bullets: [
      "Oversaw IT operations and supervised critical university systems for a campus of 12,000+ students and 500+ staff and faculty.",
      "Led an IT staff of 20, creating schedules, managing conflicts, and driving projects across all phases of the development cycle.",
      "Interfaced with internal and external clients to define technical requirements and integration goals across university systems, including Blackboard, IBM, Cisco, Dell, Box, Laserfiche, Kaltura, Pearson, Qualtrics, Citrix, and Watermark.",
      "Established processes and standards for ticket selection, client support, and closing internal requests in CBU's ticket-tracking system, ServicePRO.",
    ],
  },
  {
    title: "Information Technology Analyst",
    company: "California Baptist University",
    location: "Riverside, CA",
    start: "2021-08",
    end: "2022-07",
    date: "Aug 2021 – Jul 2022",
    type: "work",
    bullets: [
      "Served on a team of 12 as the campus's first point of contact for technical issues, supporting 12,000 students and 600+ staff across 67 departments.",
      "Handled server, network hardware, and software configuration, maintenance, installation, and troubleshooting, including print-server infrastructure, anti-virus/anti-malware, and cloud-based VOIP phone systems.",
      "Supported cloud-based SaaS platforms such as Box, Zoom, WebEx, Blackboard, Kaltura, Citrix, and VoiceThread.",
      "Partnered with 6 IT sub-departments (Networking, Card Services, Web Development, User Services, Cybersecurity, Online Learning Systems, and Telecommunications) and external partners like Dell, Apple, Microsoft, and Cisco to identify and resolve security, performance, and compliance issues.",
      "Documented, tracked, and monitored service tickets in ServicePRO, and maintained inventory and asset records in SharePoint.",
    ],
  },
  {
    title: "Developer Intern",
    company: "Kliqxe",
    location: "Kuala Lumpur, Malaysia",
    start: "2020-06",
    end: "2020-12",
    date: "Jun 2020 – Dec 2020",
    type: "internship",
    bullets: [
      "Trained in Salesforce development: Visualization Basics, Apex testing, Apex triggers, data security, user engagement, data management, and mobile app customization.",
      "Created multiple databases for retail companies using inventory management across multi-site locations.",
    ],
  },
];

/* Stats derived from the list above — used by the home page. */
window.EXPERIENCE_STATS = (function () {
  const list = window.EXPERIENCES || [];
  const roles = list.length;
  const companies = new Set(list.map((e) => e.company)).size;

  // Earliest start year → years of experience through today.
  const years = list
    .map((e) => parseInt(e.start.slice(0, 4), 10))
    .filter((y) => !Number.isNaN(y));
  const earliest = years.length ? Math.min(...years) : new Date().getFullYear();
  const yearsExperience = new Date().getFullYear() - earliest;

  return { roles, companies, yearsExperience };
})();

/* =========================================================
   NATIONAL PARKS — Riley McClain
   ---------------------------------------------------------
   Edit THIS list to update BOTH the interactive map and the
   badge grid on the Parks page.

   Each entry:
     name    — park name
     state   — state / region label
     lat,lng — map coordinates (decimal degrees)
     visited — true (filled green pin) or false (faded pin)
     year    — visit year shown on the badge ("" if none)
     note    — a short memory / highlight
     emblem  — "mountain" | "canyon" | "forest" | "water" |
               "volcano" | "glacier" | "cave" (badge art)

   Set visited:true and fill in year/note for parks you've
   actually been to. Add new parks by copying an entry.
   ========================================================= */
window.PARKS = [
  // ---------- VISITED (25) ----------
  {
    name: "New River Gorge",
    state: "West Virginia",
    lat: 37.9393,
    lng: -81.0668,
    visited: true,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Shenandoah",
    state: "Virginia",
    lat: 38.4755,
    lng: -78.4526,
    visited: true,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Great Smoky Mountains",
    state: "Tennessee / North Carolina",
    lat: 35.6118,
    lng: -83.4895,
    visited: true,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Mammoth Cave",
    state: "Kentucky",
    lat: 37.1862,
    lng: -86.1,
    visited: true,
    year: "",
    note: "",
    emblem: "cave",
  },
  {
    name: "Indiana Dunes",
    state: "Indiana",
    lat: 41.6533,
    lng: -87.0524,
    visited: true,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Cuyahoga Valley",
    state: "Ohio",
    lat: 41.2808,
    lng: -81.5678,
    visited: true,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Arches",
    state: "Utah",
    lat: 38.7331,
    lng: -109.5925,
    visited: true,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Bryce Canyon",
    state: "Utah",
    lat: 37.593,
    lng: -112.1871,
    visited: true,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Mesa Verde",
    state: "Colorado",
    lat: 37.2309,
    lng: -108.4618,
    visited: true,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Canyonlands",
    state: "Utah",
    lat: 38.2,
    lng: -109.93,
    visited: true,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Rocky Mountain",
    state: "Colorado",
    lat: 40.3428,
    lng: -105.6836,
    visited: true,
    year: "",
    note: "",
    emblem: "mountain",
  },
  {
    name: "Black Canyon of the Gunnison",
    state: "Colorado",
    lat: 38.5754,
    lng: -107.7416,
    visited: true,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Capitol Reef",
    state: "Utah",
    lat: 38.367,
    lng: -111.2615,
    visited: true,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Great Sand Dunes",
    state: "Colorado",
    lat: 37.7916,
    lng: -105.5943,
    visited: true,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Zion",
    state: "Utah",
    lat: 37.2982,
    lng: -113.0263,
    visited: true,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Channel Islands",
    state: "California",
    lat: 34.0069,
    lng: -119.7785,
    visited: true,
    year: "",
    note: "",
    emblem: "water",
  },
  {
    name: "Joshua Tree",
    state: "California",
    lat: 33.8734,
    lng: -115.901,
    visited: true,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Redwood",
    state: "California",
    lat: 41.2132,
    lng: -124.0046,
    visited: true,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Yosemite",
    state: "California",
    lat: 37.8651,
    lng: -119.5383,
    visited: true,
    year: "",
    note: "",
    emblem: "mountain",
  },
  {
    name: "Death Valley",
    state: "California / Nevada",
    lat: 36.5054,
    lng: -117.0794,
    visited: true,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Kings Canyon",
    state: "California",
    lat: 36.8879,
    lng: -118.5551,
    visited: true,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Petrified Forest",
    state: "Arizona",
    lat: 34.91,
    lng: -109.8068,
    visited: true,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Grand Canyon",
    state: "Arizona",
    lat: 36.1069,
    lng: -112.1129,
    visited: true,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Pinnacles",
    state: "California",
    lat: 36.4906,
    lng: -121.1825,
    visited: true,
    year: "",
    note: "",
    emblem: "mountain",
  },
  {
    name: "Sequoia",
    state: "California",
    lat: 36.4864,
    lng: -118.5658,
    visited: true,
    year: "",
    note: "",
    emblem: "forest",
  },

  // ---------- HOPING TO VISIT ----------
  {
    name: "Acadia",
    state: "Maine",
    lat: 44.3386,
    lng: -68.2733,
    visited: false,
    year: "",
    note: "",
    emblem: "water",
  },
  {
    name: "Congaree",
    state: "South Carolina",
    lat: 33.7948,
    lng: -80.7821,
    visited: false,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Biscayne",
    state: "Florida",
    lat: 25.49,
    lng: -80.21,
    visited: false,
    year: "",
    note: "",
    emblem: "water",
  },
  {
    name: "Everglades",
    state: "Florida",
    lat: 25.2866,
    lng: -80.8987,
    visited: false,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Dry Tortugas",
    state: "Florida",
    lat: 24.6285,
    lng: -82.8732,
    visited: false,
    year: "",
    note: "",
    emblem: "mountain",
  },
  {
    name: "Hot Springs",
    state: "Arkansas",
    lat: 34.5217,
    lng: -93.0424,
    visited: false,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Gateway Arch",
    state: "Missouri",
    lat: 38.6247,
    lng: -90.1848,
    visited: false,
    year: "",
    note: "",
    emblem: "mountain",
  },
  {
    name: "Voyageurs",
    state: "Minnesota",
    lat: 48.5,
    lng: -92.8833,
    visited: false,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Isle Royale",
    state: "Michigan",
    lat: 47.9959,
    lng: -88.9093,
    visited: false,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Theodore Roosevelt",
    state: "North Dakota",
    lat: 46.979,
    lng: -103.5387,
    visited: false,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Badlands",
    state: "South Dakota",
    lat: 43.8554,
    lng: -102.3397,
    visited: false,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Wind Cave",
    state: "South Dakota",
    lat: 43.6047,
    lng: -103.4787,
    visited: false,
    year: "",
    note: "",
    emblem: "cave",
  },
  {
    name: "Big Bend",
    state: "Texas",
    lat: 29.1275,
    lng: -103.2425,
    visited: false,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Guadalupe Mountains",
    state: "Texas",
    lat: 31.9231,
    lng: -104.8606,
    visited: false,
    year: "",
    note: "",
    emblem: "mountain",
  },
  {
    name: "Carlsbad Caverns",
    state: "New Mexico",
    lat: 32.1479,
    lng: -104.5567,
    visited: false,
    year: "",
    note: "",
    emblem: "cave",
  },
  {
    name: "White Sands",
    state: "New Mexico",
    lat: 32.7872,
    lng: -106.3257,
    visited: false,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Saguaro",
    state: "Arizona",
    lat: 32.2967,
    lng: -111.1666,
    visited: false,
    year: "",
    note: "",
    emblem: "canyon",
  },
  {
    name: "Great Basin",
    state: "Nevada",
    lat: 38.9833,
    lng: -114.3,
    visited: false,
    year: "",
    note: "",
    emblem: "mountain",
  },
  {
    name: "Yellowstone",
    state: "Wyoming / Montana / Idaho",
    lat: 44.428,
    lng: -110.5885,
    visited: false,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Grand Teton",
    state: "Wyoming",
    lat: 43.7904,
    lng: -110.6818,
    visited: false,
    year: "",
    note: "",
    emblem: "mountain",
  },
  {
    name: "Glacier",
    state: "Montana",
    lat: 48.7596,
    lng: -113.787,
    visited: false,
    year: "",
    note: "",
    emblem: "mountain",
  },
  {
    name: "Crater Lake",
    state: "Oregon",
    lat: 42.8684,
    lng: -122.1685,
    visited: false,
    year: "",
    note: "",
    emblem: "water",
  },
  {
    name: "Lassen Volcanic",
    state: "California",
    lat: 40.4977,
    lng: -121.4207,
    visited: false,
    year: "",
    note: "",
    emblem: "volcano",
  },
  {
    name: "Mount Rainier",
    state: "Washington",
    lat: 46.88,
    lng: -121.7269,
    visited: false,
    year: "",
    note: "",
    emblem: "mountain",
  },
  {
    name: "North Cascades",
    state: "Washington",
    lat: 48.7718,
    lng: -121.2985,
    visited: false,
    year: "",
    note: "",
    emblem: "mountain",
  },
  {
    name: "Olympic",
    state: "Washington",
    lat: 47.8021,
    lng: -123.6044,
    visited: false,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Haleakalā",
    state: "Hawaii",
    lat: 20.7204,
    lng: -156.1552,
    visited: false,
    year: "",
    note: "",
    emblem: "volcano",
  },
  {
    name: "Hawaiʻi Volcanoes",
    state: "Hawaii",
    lat: 19.4194,
    lng: -155.2885,
    visited: false,
    year: "",
    note: "",
    emblem: "volcano",
  },
  {
    name: "Denali",
    state: "Alaska",
    lat: 63.1148,
    lng: -151.1926,
    visited: false,
    year: "",
    note: "",
    emblem: "mountain",
  },
  {
    name: "Gates of the Arctic",
    state: "Alaska",
    lat: 67.78,
    lng: -153.3,
    visited: false,
    year: "",
    note: "",
    emblem: "glacier",
  },
  {
    name: "Glacier Bay",
    state: "Alaska",
    lat: 58.6658,
    lng: -136.9002,
    visited: false,
    year: "",
    note: "",
    emblem: "glacier",
  },
  {
    name: "Katmai",
    state: "Alaska",
    lat: 58.5972,
    lng: -155.0044,
    visited: false,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Kenai Fjords",
    state: "Alaska",
    lat: 59.9227,
    lng: -149.651,
    visited: false,
    year: "",
    note: "",
    emblem: "glacier",
  },
  {
    name: "Kobuk Valley",
    state: "Alaska",
    lat: 67.3556,
    lng: -159.2836,
    visited: false,
    year: "",
    note: "",
    emblem: "glacier",
  },
  {
    name: "Lake Clark",
    state: "Alaska",
    lat: 60.9128,
    lng: -153.4181,
    visited: false,
    year: "",
    note: "",
    emblem: "mountain",
  },
  {
    name: "Wrangell–St. Elias",
    state: "Alaska",
    lat: 61.0,
    lng: -142.0,
    visited: false,
    year: "",
    note: "",
    emblem: "mountain",
  },
  {
    name: "American Samoa",
    state: "American Samoa",
    lat: -14.2583,
    lng: -170.6821,
    visited: false,
    year: "",
    note: "",
    emblem: "forest",
  },
  {
    name: "Virgin Islands",
    state: "US Virgin Islands",
    lat: 18.3428,
    lng: -64.7486,
    visited: false,
    year: "",
    note: "",
    emblem: "water",
  },
];

/* =========================================================
   PROJECTS — Riley McClain
   ---------------------------------------------------------
   Edit THIS list to update the Projects page. Cards render
   in the order below.

   Each entry:
     title       — full title (shown in the popup header)
     heading     — short title shown on the card
     skills      — tech list shown on the card (short form)
     skillsFull  — tech list shown in the popup (can be longer)
     preview     — one-line summary on the card
     description — full description shown in the popup
   ========================================================= */
window.PROJECTS = [
  {
    title: "Salesforce Knowledge Library",
    heading: "Knowledge Library",
    skills: "Custom LWC · Experience Site · Flows",
    skillsFull:
      "Custom Lightning Web Components · Flows · Experience Sites · Knowledge__kav",
    preview: "Knowledge Library custom Experience Site (2026).",
    description:
      "An Experience Site that lets users view knowledge articles created by Knowledge Managers. Built to give users a deeper understanding of Compassion International and to provide documentation. Includes a backend that lets users request articles, which are routed to a Knowledge Manager's queue for creation.",
  },
  {
    title: "VEX U Robotics",
    heading: "CBU VEX U Team",
    skills: "C++ · Team Leadership · Project Management",
    skillsFull:
      "C++ · Autonomous Programming · Robotics · Team Leadership · Project Management · Agile Collaboration",
    preview: "Co-led software team and became Project Manager of the team.",
    description:
      "Competed in the VEX U collegiate robotics competition. Started as co-lead for software development, writing the autonomous and driver-control code in C++ . Later stepped into an administrative assistant role, acting as project manager for the entire team — coordinating schedules, tracking tasks and deadlines, and keeping software, hardware, and design efforts aligned toward competition goals.",
  },
  {
    title: "Flight Simulator Log — Capstone",
    heading: "Flight Simulator Log",
    skills: "C# · .NET · Firebase",
    skillsFull: "C# · .NET · Firebase Authentication · Windows 11",
    preview: "Capstone Windows app for CBU School of Aviation (SU–FA 2024).",
    description:
      "A Windows application built for the CBU School of Aviation to track and log student flight simulator time. Delivered a minimum viable product that let students sign in with their student ID using Firebase Authentication.",
  },
  {
    title: "Drone Livestream Tracker — Jr. Design",
    heading: "Drone Livestream Tracker",
    skills: "Flutter · Firebase · AI",
    skillsFull: "Flutter · Google Firebase · Authentication · AI",
    preview: "AI drone tracking with a Flutter desktop app (SP 2024).",
    description:
      "A desktop app in Flutter connected to Google Firebase and Authentication that let users sign in, access, and log YouTube livestreams. Integrated an AI component connected to a DJI Mini drone that boxes humans in a livestream, viewable through a media player widget.",
  },
  {
    title: "Embedded Systems Projects",
    heading: "Embedded Systems",
    skills: "Arduino C++ · BLE · ESP32",
    skillsFull: "Arduino C++ · C · Platform.io · BLE · I2C · ESP32",
    preview: "BLE tag game, weather station, and robot on ESP32 (SP 2024).",
    description:
      "A collection of embedded projects on M5 Core Stack ESP32 hardware: a two-player tag game connecting two ESP32s over BLE with an Adafruit Mini I2C gamepad; a weather program reading from APIs and I2C Adafruit temperature/humidity sensors; and a small BLE-controlled robot driven by motors and an I2C gamepad.",
  },
  {
    title: "Community Music Queue",
    heading: "Community Music Queue",
    skills: "HTML · CSS · JavaScript",
    skillsFull: "HTML · CSS · JavaScript · Spotify",
    preview: "Shared Spotify group queue web app (SP 2024).",
    description:
      "A website where users can add music to a shared community queue. Different users connect through their Spotify accounts and join a group queue together.",
  },
  {
    title: "Picture Bingo — Mobile",
    heading: "Picture Bingo",
    skills: "Flutter · Firebase",
    skillsFull: "Flutter · Google Firebase · Authentication",
    preview:
      "Mobile picture bingo game using device camera and location (FA 2023).",
    description:
      "A mobile game that lets users create a picture bingo on their phone. Used Flutter packages to access device properties such as location and camera.",
  },
  {
    title: "Beneficiary Photos — Compassion International",
    heading: "Beneficiary Photos",
    skills: "Mobile UI · Production Release",
    skillsFull: "Mobile UI · Bug Fixing · Dev → Stage → Prod",
    preview:
      "Shipped UI fixes to the Play Store at Compassion International (SU 2023).",
    description:
      "Fixed UI bugs around text input in Beneficiary Photos and shipped changes from dev to stage to production. The work reached the Google Play Store in version 2.3.6, live from November 22, 2023 to September 10, 2024.",
  },
  {
    title: "Kliqxe Retail CRMs",
    heading: "Kliqxe Internship",
    skills: "Salesforce · Apex",
    skillsFull: "Salesforce Admin · Apex · Data Management",
    preview: "Built Salesforce CRMs for retail clients (2020).",
    description:
      "Starting in 2020 I worked alongside developers learning Salesforce and its many uses, building CRM databases for retail clients with inventory management across multi-site locations.",
  },
];
